language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: lbxa3fna/g69VM8CyH8B/KuBTGCgrFldsrR46yOnI+u7Tiv+ifgivmqf7rmCgJYl6VmtDH5vPtN3uPsvrkYkWXuw8lVAEOY5IDH1fcFmD07QjcgsHLmQjeQXf7EL+9Fq4l+96oariDFWqUz5QHj+bu4n36kWtXfjxuEZmqTVY0gy+2uK/2nphZOnuVKktET43aM9nH/k1Hv5BTx2vBV2J9vQckHG6rhaplnsqYlwke5LPqxMjXw+INZOvyvhLi7GGVCq0El0Zu3rtOA+C3VVs54uCILP9EKL+kYXWyATl1o6dN8hNLtFyjDSqYfm/OrgtxP8EYanqZSRfTIUy1XMmM4OHfAeFCHbmSXwaYgirYWPvVTc5/fllJo1+qb2QWSZgQ1RiHLvckPf7txWupDfckw+mQkUKboCcjTzjutA0KibPjgLWOxV1yAN3WhEe8WfSRkZDug4VLChUund3esNPBNaPGDNcQnVNIt/wOnoe4GDdQ3A4oxKICZ+CBHg3qho7O2a31pBAMHY+XcjxuE6Q+sd/VAzOoCaZz8XS0Han9OTG1DX126KWdlhXeaOVq62tzsgNUFA7F4cfPrevfzQyZBrBk5XCDTryJFomPeUwM+VAvsQC6ovVFcgWFvlkx1ERXRVpoHDr214mpBvNTeaxrKJbnsKDbSM7Q3u0vOUKyw=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
